services:
    limiterstore:
        image: redis:7-alpine
        container_name: limiterstore
        restart: always
        ports:
            - "6379:6379"
        command: >
            redis-server
                --requirepass mypass
                --databases 8
        volumes:
            - redis-data:/data

volumes:
    redis-data:
